---
- name: Install dependencies for centos messaging consumer
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run centos messaging consumer
      dnf:
        name:
          - python3-celery
          - python3-redis
          - redis # redis-cli
          - python3-boto3 # AWS SDK
          - python3-pycurl # ^
          - python3-click
          - git # setuptools-scm
          - python3-setuptools_scm
          - python3-paho-mqtt
          - python3-cryptography
        state: present
